### PR TITLE
2016.12.02. Add more mockup functionalities

### PR DESCRIPTION
**Pull request by IvarsKarpics**
* AbstractCollect: fixed bug when no ispyb was avialable and store_image failed
* CollectMockup : added few lines to test a failed collection
* EnergyScanMockup: added chooch graph
* DetectorMockup : added exposure time limits
* SampleChangerMockup: added signal for the progressbar

### CODE REVIEW

**Comment by IvarsKarpics** [comment]
Thanks!

**Comment by mguijarr** [comment]
You're welcome.

By the way... We just spoke about abstract objects and mockups, and all the work there is left to do on beamlines (not just at ESRF but also other institutes) to really finish them and have implementations ready. In this sense, the 2.2 branch failed to reach the goal.

Now we should soon preparing 2.3, I would like to release 2.3 only when implementations at several sites really exist, in order to make sure everything is clean, tested and stable... If when 2.3 is out, several institutes rely on it and there are abstract classes, mockups and implementations ready for all hardware objects it would be a great achievement.

**Comment by IvarsKarpics** [comment]
Hi,

What do you mean with "implementations at several sites"? For me it would be good to understand what hwobj and abstract classes are used to have an overview. Regarding the mockups: quite a lot are available in master and during the release of 2.3 we should go through them an agree on API. In principle it would be a good exercise to check all abstract and generic classes and define a clear API.
Maybe I am not talking now about some Christmas miracles, but a stable 2.3 and clearly defined could be achieved. Maybe an extra day for developers after or before mxcube meeting?

**Comment by beteva** [comment]
I strongly support the idea of understanding ´what hwobj and abstract classes are used for´  and we, ´all different sites´ should agree on the subject. Regarding the mockups - a sometimes significant difference has been introduced between the 2.1 and 2.2 method signatures, and I do not agree to reuse the same thing for 2.3. Before accepting any of them, we should go through and agree on the API. BTY I think we should transfer this discussion to https://github.com/mxcube/HardwareObjects/issues/82

**Comment by IvarsKarpics** [comment]
I fully agree. Further comments I will move to #82

**Pull request merged**
