### PR TITLE
Execution issue 

### PR DESCRIPTION
**Pull request by meguiraun**
same as previous one

### CODE REVIEW

**Comment by mguijarr** [comment]
@meguiraun I had to revert your merge request, because `set_running` doesn't exist ?

**Comment by meguiraun** [comment]
@mguijarr, oopss... I will re-submit a pr that checks if the method exists.

**Comment by mguijarr** [comment]
@meguiraun Thanks. I am asking myself why would we need this code now? What is it solving? Where is `set_running` present ? Maybe it's only in master branch ? (just wondering)

**Comment by meguiraun** [comment]
This is just to make sure that executed or failed tasks are not run again on the next queue execution. You are right, `set_running` is only available in master.

**Comment by meguiraun** [comment]
see #233

**Comment by mguijarr** [comment]
Ok. I merged it.

**Pull request merged**
