### PR TITLE
Xaloc specific 2.2

### PR DESCRIPTION
**Pull request by jordiandreu**
Adding specific Xaloc Hardware Objects

### CODE REVIEW

**Comment by IvarsKarpics** [comment]
Quite massive PR that can not be automaticaly merged.
I guess you should update your fork and make a pull request once again

**Comment by mguijarr** [comment]
Try to rebase your branch on master before doing the PR again?

**Comment by jordiandreu** [comment]
Sorry, I was in 2.2 branch. Merging to 2.2 would be straight forward but I will rebase to master an create the pull request again.

Jordi

Enviat des del meu iPhone

El 16 juny 2016, a les 16:21, Matias Guijarro notifications@github.com va escriure:

**Comment by mguijarr** [comment]
Maybe it's best if you make the PR for the 2.2 branch first ? And another one for master then

**Comment by jordiandreu** [comment]
I can submit the PR again but against the 2.2 branch. This integration will be straight forward. I do have also another feature branch related to the Qt4_LimaVideo in the same situation ( I did not PR yet). So, do you want me to submit both PR against the 2.2 branch? I thought that the standard procedure would be to PR against the master branch? 

Cheers

Enviat des del meu iPhone

El 16 juny 2016, a les 21:01, Matias Guijarro notifications@github.com va escriure:

**Comment by mguijarr** [comment]
If your changes have been done on 2.2, and you're only adding Xaloc specific files, I think it's more
convenient for you to make the PR to 2.2 because it would include your files with a stable release
of MXCuBE.
If you have a bug fix*, it has to be submitted to 2.2 - maybe this is the case with Qt4_LimaVideo ?
*: we tolerate small improvements too

In any case, all PRs to 2.2 have to be done in master as well.

If your changes are completely new features and/or untested code, then it has to be done in master only.

**Comment by jordiandreu** [comment]
On 06/17/2016 08:32 AM, Matias Guijarro wrote:

> If your changes have been done on 2.2, and you're only adding Xaloc 
> specific files, I think it's more
> convenient for you to make the PR to 2.2 because it would include your 
> files with a stable release
> of MXCuBE.
> If you have a bug fix*, it has to be submitted to 2.2 - maybe this is 
> the case with Qt4_LimaVideo ?
> *: we tolerate small improvements too
> 
> I created 2 new PR. One for the specific XALOC HwObj folder (which did 
> not exists yet) and a second one for the Basler camera support in Qt4 
> which has been tested here at ALBA. Both PR have been submitted to 2.2 
> branch without conflicts.
> 
> In any case, all PRs to 2.2 have to be done in master as well.
> 
> Should I also apply these changes as two new feature branches created 
> from master HEAD and create 2 new PR to be merged with master branch??
> 
> If your changes are completely new features and/or untested code, then 
> it has to be done in master only.
> 
> The Qt4_LimaVideo has been tested @ ALBA with the Basler camera but a 
> cannot check that the part related to the prosilica camera still work 
> (that SHOULD, of course)
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub 
> https://github.com/mxcube/HardwareObjects/pull/69#issuecomment-226691113, 
> or mute the thread 
> https://github.com/notifications/unsubscribe/AH8ZEKcDevYSALDAwbzvw88EEzbgMhZ8ks5qMj-VgaJpZM4I3SEA.

## 

ALBA Synchrotron http://www.albasynchrotron.es

```
Jordi Andreu
```

Controls Section - Computing Division
jandreu@cells.es| (+34) 93 592 4057
ALBA SYNCHROTRON LIGHT SOURCE
Carrer de la Llum 2-26 | 08290 | Cerdanyola del Vallès| Barcelona | 
Spain http://www.albasynchrotron.es/AboutUs/Access

www.albasynchrotron.es http://www.albasynchrotron.es| jandreu@cells.es 
mailto:jandreu@cells.es

*_Please, do not print this e-mail unless it is absolutely necessary.
*_Si heu rebut aquest correu per error, us informo que pot contenir 
informació confidencial i privada i que està prohibit el seu ús. Us 
agrairíem que ho comuniqueu al remitent i l'elimineu. Gràcies.
Si ha recibido este correo por error, le informo de que puede contener 
información confidencial y privada y que está prohibido su uso. Le 
agradeceré que lo comunique a su remitente y lo elimine. Gracias.
If you have received this e-mail in error, please note that it may 
contain confidential and private information, therefore, the use of this 
information is strictly forbidden. Please inform the sender of the error 
and delete the information received. Thank you.

**Pull request closed without merging**
