### PR TITLE
2016.01.15. Added new DESY hwobj

### PR DESCRIPTION
**Pull request by jan-meyer**

### CODE REVIEW

**Comment by IvarsKarpics** [comment]
Added DESY directory and new hwobj for camera.
Accepting PR.

**Comment by IvarsKarpics** [comment]
Sorry for spamming...
Some lesson learned how to accept PRs.

**Comment by mguijarr** [comment]
Thanks for this.

It would be good to have the same pull request for 2.1 branch if you could do it ?

**Comment by IvarsKarpics** [comment]
Hi,

Not sure how to do this. In a clean way we have to merge 2.1 in master and come up with 2.2 (see my email). Otherwise what could be the best way how to do this? Sorry, but I am still learning how to work with git and pull requests...

**Comment by mguijarr** [comment]
AFAIK @jan-meyer can do it, by making a new PR asking to merge in HardwareObjects/2.1 instead of HardwareObjects/master.

Completely agree with merging 2.1 into master and creating 2.2 ; I just replied your email ;)

**Comment by jan-meyer** [comment]
I don't think this is necessary. Nobody but P11 is using it this HWO and 
the P11 installation is in a very alpha state. So I can see no reason to 
include a single component of it into a release version.
But sure, if you want me to do a pull request, I will do it.

On 15.01.2016 11:44, Matias Guijarro wrote:

> AFAIK @jan-meyer https://github.com/jan-meyer can do it, by making a
> new PR asking to merge in HardwareObjects/2.1 instead of
> HardwareObjects/master
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mxcube/HardwareObjects/pull/7#issuecomment-171930876.

## 

---

Jan Meyer
Beamline Support P11

Deutsches Elektronen-Synchrotron
Notkestr. 85
47c / L136
22607 Hamburg
Germany

phone:  +49-40-8998-5773

## e-mail: jan.meyer@desy.de

**Pull request merged**
