### PR TITLE
to merge maxlab (bl911-3) HardwareObjects

### PR DESCRIPTION
**Pull request by JieNanMAXIV**
1. Most of changes are new HO for BL9113 at MAXLAB
2. about MicrodiffMotor.py,
   otherwise motor_name was not assigned with any value, error with ho.init()
3. about  queue_model_objects_v1.py, 
   init_from_sc_basket has different arguments when called in dc_tree_widget.py. The method defined in branch 2.1 works

### CODE REVIEW

**Comment by IvarsKarpics** [comment]
Hi,

From my side pull request is fine and I can accept it. If nobody is against it then I will merge it.
In the next meeting we should agree on a schema how we handle pull requests. For example if nobody is against then pull request should be merged within few days.

**Comment by mguijarr** [comment]
I agree as well.

However we need to merge to 2.1 too - I propose the following: I accept the PR to merge into master,
then I will try to extract the commits for the new Maxlab objects and push them into 2.1 since the 3
other changes are already solved in 2.1.
We need to merge 2.1 into master at some point, or better: to create 2.2 and then merge 2.2 with master...
Remember 2.1 should be the "stable"/bug fixes only branch, and master is development. Also for MXCuBE 3 we rely on 2.1.
I am going to make HardwareObjects as a submodule of MXCuBE 2.1 branch as it is done for master,
I never had time to finish this properly before.

**Comment by beteva** [comment]
Hello, in 2.1 I´ve created a new HO to handle the MD2 motors, based on the AbstarctMotor.py. It has been named MD2Motor, but has the same methods as the MicrodiffMotor plus bugs fixed for the Limits. Do you think it is possible to remove the current MicrodiffMotor and rename the MD2Motor to MicrodiffMotor. As the methods are compatible you do not have to change anything in  the other HOs.

**Comment by IvarsKarpics** [comment]
Hi,
Also fine from my side. could we add also MDAperture? I have one named EMBLAperture which is working with md2 and md3 via exporter.
My suggestion is to summarize all hwobj and before going to ALBA set 2.2. tag, keep it stable and use it as a reference in beamlines.
I did some major rework of AbstractMulticollect and queue_entry to allow interleaced collections and advanced scans like xray centring. This could be interesting also for other sites. But this needs more testing from my side and some agreement on few hardware objects.

**Pull request merged**
