### PR TITLE
a few changes for the MAXIV HardwareObjects

### PR DESCRIPTION
**Pull request by JieNanMAXIV**

### CODE REVIEW

**Comment by mguijarr** [comment]
Hello :)
I have a remark regarding BIOMAXMiniDiff.py ; I think it would be wise to write the code based on Ivars' GenericDiffractometer. On my side I will (at some point...) re-write our classes to inherit from GenericDiffractometer.
See #18

**Comment by IvarsKarpics** [comment]
That would be great if we come up with a common GenericDiffractometer and actually use it. As I said, it is a first version and things can be discussed.
How about master? Should there be an another PR to the master branch? Or we time to time push 2.2. to master. From my side I will work on bug fixes on 2.2. branch. And new developments will go to master.

**Comment by JieNanMAXIV** [comment]
Yes, thanks for the advice! This BIOMAXMiniDiff.py was a quick modification of our previous MAXLAB one, just to have something working. I will write a new one using Ivars’ GenericDiffractometer.

**Comment by JieNanMAXIV** [comment]
Personally for the moment, I would prefer only push the MAXIV HardwareObjects to the 2.2, as we are still under development and it will for sure have a lot of changes.

In the future, probably it’s nice to push to both the master and 2.2 or other 2.x stable branch.

**Pull request merged**
