### PR TITLE
2016.09.02. Method to save/load queue in/from a file

### PR DESCRIPTION
**Pull request by IvarsKarpics**
Added methods to be able to save queue in and load from a file.
- QueueModel.py: added save_queue, load_queue, save_on_exit and load_on_start methods
- queue_entry.py: fixed bug when Characterisation failed. Cleaned up the launch of parallel processing.

### CODE REVIEW

**Comment by marcus-oscarsson** [comment]
Thanks Ivars :).

Its great that we can save the queue now :)

I'm personally not sure that the save_on_exit and load_on_start should be part of the QueueModel. Its maybe more logic that belongs to the application using the queue. I don't really see a problem with it being like this so I don't mind merging it.

Ciao
Marcus

**Comment by IvarsKarpics** [comment]
Hi Marcus!

I would be careful with saying that we can save queue :) It needs more testing to be fully available.
I agree to your suggestion about moving the save and load function to the higher level. Do you know how it is done in the web version? Is the serialized queue always stored in redis data base? Is it possible to save the queue also manually and load it later?
Maybe I am now reinventing the wheel with this queue saving.

**Comment by marcus-oscarsson** [comment]
Hi Ivars,

I see but the idea is that we can save the queue :), its a great initiative something we have talked
about but never found the time to do. Yes me and the other guys are working on that for the moment. I don't think you are re-inventing the wheel because its fairly recent development. I would be happy if there is something we can share with each other, so let me know if you would like to work on this together. The only constraint we have is that we need to be able to handle the queue as JSON data :)

The queue is currently saved in redis after each action, I don't know if its the best way
but it somehow makes sense. I wrote something that serializes the queue into JSON but it only
contains the parameters for DataCollections and Characterisations. I honestly don't remember if I included the centered positions or not but it should not be a problem to add. The binary data for
the snapshots are not included, they could be included as base64 encoded text but I don't know
if its really necessary. This since the snapshots are typically taken on collect and thus should already be in lims for that collection. But its true that its nice to have them, especially i the Qt version since you have the snapshot in the data collection parameters, which we currently don't have in the web version.

Its currently not possible to load and save the queue manually but we have discussed it here at ESRF. It would be a nice feature.

**Comment by marcus-oscarsson** [comment]
See the queue_to_\* methods in (if you like to have some more info):
https://github.com/marcus-oscarsson/mxcube3/blob/master/mxcube3/routes/Utils.py

Ill try to take a more in depth look into the serialization code you wrote to see if we can 
interface with that :)

Have a nice weekend !,
Marcus

**Comment by IvarsKarpics** [comment]
Hi Marcus!

I see quite an elaborate code. Great work!
What I did in the QueueModel to save the queue is much simpler : file contains just information about task groups (dictionaries with encoded task group and sample location). I did not see any need to save information about samples or baskets.
I see the point to save the queue after each action (it actually allows to implement undo and redo functions) and not to store image snapshots (they should be a fresh ones before the collection).

I think it would be great if we could come up with a uniform queue serialization. One option would be to move some code from routes/Utils.py to QueueModel or QueueManager. Would that be durable?

Lets discuss this next week,
Have a nice weekend too!

Ivars

**Pull request merged**
